name: CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  REGISTRY: docker.io

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Test Go skills
      run: |
        for skill in */; do
          if [ -f "$skill/go.mod" ]; then
            echo "Testing $skill"
            cd "$skill"
            # Skip skills that require local dependencies not available in CI
            if grep -q "replace.*=> \.\./\.\./loqa-hub" go.mod; then
              echo "Skipping $skill - requires local loqa-hub dependency not available in CI"
            else
              go test ./...
            fi
            cd ..
          fi
        done

    - name: Quality check
      run: |
        for skill in */; do
          if [ -f "$skill/go.mod" ]; then
            echo "Quality check for $skill"
            cd "$skill"
            # Skip skills that require local dependencies not available in CI
            if grep -q "replace.*=> \.\./\.\./loqa-hub" go.mod; then
              echo "Skipping $skill quality check - requires local loqa-hub dependency not available in CI"
            else
              go fmt ./...
              go vet ./...
            fi
            cd ..
          fi
        done

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Docker images
      run: |
        for skill in */; do
          if [ -f "$skill/Dockerfile" ]; then
            echo "Building Docker image for $skill"
            docker build -t ${REGISTRY}/loqalabs/skill-${skill%/}:latest "$skill"
          fi
        done