name: Check Commit Messages

on:
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  pull-requests: read

jobs:
  commit-check:
    name: Check Commit Messages
    uses: loqalabs/.github/.github/workflows/quality/commit-message-check.yml@main
    with:
      ai-attribution-check: true
      allow-merge-commits: true