name: Security Scan

on:
  schedule:
    # Weekly security scan on Sundays at 4 AM UTC
    - cron: '0 4 * * 0'
  workflow_dispatch:

jobs:
  security:
    name: Security Analysis
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      security-events: write
      actions: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: go

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.1'

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.4.0

    - name: Run golangci-lint on all Go skills
      run: |
        for skill in */; do
          if [ -f "$skill/go.mod" ]; then
            echo "Linting Go skill: $skill"
            cd "$skill"
            golangci-lint run --config ../.golangci.yml || echo "Linting failed for $skill, continuing..."
            cd ..
          fi
        done

    - name: Build Go skills for CodeQL
      run: |
        for skill in */; do
          if [ -f "$skill/go.mod" ]; then
            echo "Building Go skill: $skill"
            cd "$skill"
            go build -v ./... || echo "Build failed for $skill, continuing..."
            cd ..
          fi
        done

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'